#################################################
# Dockerfile for jlnetosci/r-minimal-knitr:1.43 #
#################################################

FROM rhub/r-minimal:4.3.1
LABEL maintainer="João L. Neto (https://github.com/jlnetosci/)"

RUN installr -d knitr